### PR TITLE
fix: use clusterRole for gcjobs until jx gitops helmfile move doesn't change namespace

### PR DESCRIPTION
**Pull request by yelhouti**
… change namespace

### CODE REVIEW

**Comment by rawlingsj** [comment]
Is there anymore information why this needs to change to a clusterrole?  The title says "until jx gitops helmfile move doesn't change namespace" but I'm not too sure what that means, is there an issue somewhere else that this change is working around?

**Comment by yelhouti** [comment]
@rawlingsj this change was recently introduced to use roleBinding instead of clusterRoleBinding, which I totally understand.

But unfortunately doesn't work inside the pipeline because of:
https://github.com/jx3-gitops-repositories/jx3-kubernetes/blob/c1ab2d47c5666cc3f670850a60f591555af2171f/versionStream/src/Makefile.mk#L127

this command seems to override the namespace in the even if it's set, I think this should not be the case.
For now, since we don't want to touch until we know more, we revert to this version.

**Comment by ankitm123** [comment]
https://github.com/jenkins-x-charts/jxboot-helmfile-resources/pull/406 -> this is the PR. If we can even get the role created in the jx-git-operator ns, it would be nice. For now it just breaks.
I will take a look at the jx gitops subcommand, and see if there is a fix, for now, cluster role seems to be the only solution ...
From my local cluster:
```
k logs jx-gcjobs-27398670-ld9hq
error: jobs.batch is forbidden: User "system:serviceaccount:jx:jx-gcjobs" cannot list resource "jobs" in API group "batch" in the namespace "jx-git-operator"

```

**Comment by nicolaerosia** [comment]
any update?

**Comment by yelhouti** [comment]
This should he been fixed in the last version (due to jx gitops being fixed)

**Comment by nicolaerosia** [comment]
Was it merged? Can you please link the PR?

**Comment by danisafta** [comment]
is this still going to be merged? I am using GitOps v0.7.0 and still have this in the logs: `error: jobs.batch is forbidden: User "system:serviceaccount:jx:jx-gcjobs" cannot list resource "jobs" in API group "batch" in the namespace "jx-git-operator"
`

**Comment by chrislovecnm** [comment]
This does not seem to be fixed.  What is blocking this merge?

**Comment by yelhouti** [comment]
No this won't merged the jx gitops bug was fixed and we will be able to install the rile in the gitops namespace. Don't know when the gitops fix will be available though

**Comment by chrislovecnm** [comment]
@yelhouti where is the PR/issue?

**Comment by yelhouti** [comment]
@chrislovecnm looks like this one: https://github.com/jenkins-x-plugins/jx-gitops/commit/b65fb118e045db336a8b759b1677d327714b79ef but I don't know know how well it works

**Comment by ankitm123** [comment]
@yelhouti I think for now, this is what we can merge. Going to re-open it,

**Comment by chrislovecnm** [comment]
@ankitm123 should we move these yaml files into the installation of the jx-git-opeartor?

**Pull request merged**
